image:
  - Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Debug
  - Intermediate
  - Profile
  - Release

install:
  - git submodule update --init
  - cinst 7zip
  - if "%PLATFORM%" equ "x86" set BITS=32
  - if "%PLATFORM%" equ "x64" set BITS=64
  - if "%PLATFORM%" equ "x86" set ARCH=x86
  - if "%PLATFORM%" equ "x64" set ARCH=x86_64
  - if "%PLATFORM%" equ "x86" set PLAT=Win32
  - if "%PLATFORM%" equ "x64" set PLAT=x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars%BITS%.bat"
  - if "%CONFIGURATION%" equ "Debug" set WX_CONFIG=debug
  - if "%CONFIGURATION%" neq "Debug" set WX_CONFIG=release
  - curl -fsS -o fbx.exe http://download.autodesk.com/us/fbx/2018/2018.1.1/fbx20181_1_fbxsdk_vs2015_win.exe
  - "%ProgramFiles%\\7-Zip\\7z.exe" x fbx.exe -oDependencies\\fbx
  - set FBX_SDK=Dependencies\fbx

build_script:
  - cmd: cd Dependencies
  - cmd: ..\premake --core --wx-config %WX_CONFIG% --architecture=%ARCH% vs2017
  - cmd: msbuild Build\Dependencies.sln /p:Configuration=%CONFIGURATION% /p:Platform=%PLAT% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal
  - cmd: cd ..
  - cmd: premake --core --architecture=%ARCH% vs2017
  - cmd: msbuild Build\Core.sln /p:Configuration=%CONFIGURATION% /p:Platform=%PLAT% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal
