image:
  - Visual Studio 2015

platform:
  - x86
  - x64

configuration:
  - Debug
  - Intermediate
  - Profile
  - Release

install:
  - git submodule update --init
  - cinst 7zip
  - if "%PLATFORM%" equ "x86" set VCVARS=bin\vcvars32.bat
  - if "%PLATFORM%" equ "x64" set VCVARS=bin\amd64\vcvars64.bat
  - if "%PLATFORM%" equ "x86" set ARCH=x86
  - if "%PLATFORM%" equ "x64" set ARCH=x86_64
  - if "%PLATFORM%" equ "x86" set PLAT=Win32
  - if "%PLATFORM%" equ "x64" set PLAT=x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\%VCVARS%"
  - if "%CONFIGURATION%" equ "Debug" set WX_CONFIG=debug
  - if "%CONFIGURATION%" neq "Debug" set WX_CONFIG=release
  - curl -fsS -o fbx.exe http://download.autodesk.com/us/fbx/2018/2018.1.1/fbx20181_1_fbxsdk_vs2015_win.exe
  - 7z.exe x fbx.exe -oDependencies\fbx
  - set FBX_SDK=%CD%\Dependencies\fbx

build_script:
  - cmd: cd Dependencies
  - cmd: ..\premake --core --wx-config=%WX_CONFIG% --architecture=%ARCH% vs2015
  - cmd: msbuild Build\Dependencies.sln /p:Configuration=%CONFIGURATION% /p:Platform=%PLAT% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal
  - cmd: cd ..
  - cmd: premake --core --architecture=%ARCH% vs2015
  - cmd: msbuild Build\Engine.sln /p:Configuration=%CONFIGURATION% /p:Platform=%PLAT% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal

notifications:
  - provider: Slack
    auth_token:
      secure: D4bTJ70wSto2H4w1nPP+4d1aPHGP4zdao+6vPtebU5uxZnVj0YLhK4VsJ695fxR+6e3YWaSvlDlX43FFoZT7yfYEXWKqbXBeRo+IqD4+5Fg=
    channel: '#general'
