language: cpp
dist: trusty
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
matrix:
  include:
  - os: linux
    compiler: gcc
    env:
    - WX_CONFIG=debug
    - CONFIG=debug
  - os: linux
    compiler: gcc
    env:
    - WX_CONFIG=release
    - CONFIG=intermediate
  - os: linux
    compiler: gcc
    env:
    - WX_CONFIG=release
    - CONFIG=profile
  - os: linux
    compiler: gcc
    env:
    - WX_CONFIG=release
    - CONFIG=release
  - os: osx
    compiler: clang
    env:
    - WX_CONFIG=debug
    - CONFIG=debug
  - os: osx
    compiler: clang
    env:
    - WX_CONFIG=release
    - CONFIG=intermediate
  - os: osx
    compiler: clang
    env:
    - WX_CONFIG=release
    - CONFIG=profile
  - os: osx
    compiler: clang
    env:
    - WX_CONFIG=release
    - CONFIG=release
git:
  submodules: false
before_install:
- git submodule update --init --recursive
- "./.travis.before_install.$TRAVIS_OS_NAME.sh"
script:
- cd Dependencies
- "../premake.sh --core --wx-config=${WX_CONFIG} gmake"
- make -C Build -j4 config=${CONFIG}
- cd ..
- "./premake.sh --core gmake"
- make -C Build -j4 config=${CONFIG}
notifications:
  slack:
    secure: WXKd9V0hvXKC5CSn1as3j/SMHQBAUvBQcL+FAkgoG0ZzipyUH0LzkgW9LlRqr7966Qvq4E3lGMbYT1RF+1Ij2x23z9oQ7UmlhMeKN8Hv8oOUPEbV3aHCw/B7B4XHlTysKs5oz7KtApFQ6gCYUQP7kARFJs/lvucKWfOihjShKXU=
